apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: checks-claim
  name: checks-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
