apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: compliance-ui
  name: compliance-ui
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: compliance-ui
  template:
    metadata:
      labels:
        app: compliance-ui
    spec:
      containers:
      - image: cdssnc/compliance-ui
        imagePullPolicy: Always
        name: compliance-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: PREACT_APP_API_URL
            value: /compliance/api
          - name: PORT
            value: "4000"
          - name: PREACT_APP_PUBLIC_PATH
            value: /compliance/ui/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
