apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: compliance-api
  name: compliance-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: compliance-api
  template:
    metadata:
      labels:
        app: compliance-api
    spec:
      containers:
      - image: cdssnc/compliance-api
        imagePullPolicy: Always
        name: compliance-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: compliance-checks
            mountPath: /checks
        env:
          - name: CHECKS_PATH
            value: /checks
          - name: DEFINITIONS_URL
            value: https://raw.githubusercontent.com/cds-snc/ITSG-33-definitions/master/ITSG-33a.yaml
          - name: CERTIFICATION_URL
            value: https://raw.githubusercontent.com/cds-snc/ITSG-33-baselines/master/minimum-per-release.yaml
      initContainers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-ac-2'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application follows Account Management policy as laid out in documentation.'
            - name: SATISFIES
              value: 'AC-2'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/account-management.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-au-2-apiserver'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The AWS Node Pod logs all API requests that make infrastructure changes.'
            - name: SATISFIES
              value: 'AU-2,AU-3,AU-3 (1)'
            - name: NEEDLE
              value: 'aws-node'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-au-6'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The organization does audit reports and reviews in line with written policy.'
            - name: SATISFIES
              value: 'AU-6'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/audit-review.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-au-8-fluentd'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Fluentd for logging.'
            - name: SATISFIES
              value: 'AU-8,AU-8 (1),SI-11'
            - name: NEEDLE
              value: 'fluentd'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/roles-check-compliance:latest'
          imagePullPolicy: Always
          name: 'roles-check-compliance-ac3-ac6'
          env:
            - name: ORIGIN
              value: 'cdssnc/roles-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses appropriate roles to manage API access'
            - name: SATISFIES
              value: 'AC-3,AC-6'
            - name: NEEDLE
              value: 'system:aws-cloud-provider'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-kube-hunter'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Kube hunter for vulnerability scanning.'
            - name: SATISFIES
              value: 'CA-2 (2),RA-5,SA-11,SA-15 (4)'
            - name: NEEDLE
              value: 'kube-hunter'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-ca'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application undergoes penetration testing as specified in documentation.'
            - name: SATISFIES
              value: 'CA-8,CA-8 (1)'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/penetration-testing.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-cm-7'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses pod security policies to restrict ports and user priviliges.'
            - name: SATISFIES
              value: 'CM-7'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/manifests/base/pod-security-policy.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-cm'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses a packages.json to manage the information inventory in source control with a log of changes by users.'
            - name: SATISFIES
              value: 'CM-8,CM-8 (1),CM-8 (4)'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/package.json'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-cm-2'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses kubernetes configuration files to manage its state and information inventory in source control with a log of changes by users.'
            - name: SATISFIES
              value: 'CM-2,CM-6 (1),CM-8,CM-8 (1),CM-8 (4)'
            - name: URL
              value: 'https://raw.githubusercontent.com/cds-snc/mrpinchy-confession-box/master/manifests/base/kustomization.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-ia-5-7'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses Seekret to scan for keys in the build pipeline.'
            - name: SATISFIES
              value: 'IA-5 (7)'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/cloudbuild.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-pl-8'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application follows the guidelines laid out in the Information Architecture guide.'
            - name: SATISFIES
              value: 'PL-8'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/information-architecture.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sa-11'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application developers follow a security assessment plan.'
            - name: SATISFIES
              value: 'SA-11'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/security-assessment-plan.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sa-11-1'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses an ESLint file to do so static code analysis.'
            - name: SATISFIES
              value: 'SA-11,SA-11 (1)'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/.eslintrc.json'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/github-reviews-check-compliance:latest'
          imagePullPolicy: Always
          name: 'github-reviews-check-compliance-sa-11-4'
          env:
            - name: ORIGIN
              value: 'cdssnc/github-reviews-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The application performs code review on its pull requests.'
            - name: SATISFIES
              value: 'SA-11,SA-11 (4)'
            - name: REPO_URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-sa-12-kritis'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Kritis to block deployment of vulnerable container images.'
            - name: SATISFIES
              value: 'SA-12'
            - name: NEEDLE
              value: 'kritis'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-sc-7-istio'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Istio to monitor incoming and outgoing data and encrypt communication between pods.'
            - name: SATISFIES
              value: 'SC-7'
            - name: NEEDLE
              value: 'istio'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sc-12'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses symmetric keys to use secrets in the build pipeline.'
            - name: SATISFIES
              value: 'SC-12,SC-13'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/cloudbuild.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/github-issues-check-compliance:latest'
          imagePullPolicy: Always
          name: 'github-issues-check-compliance-si-2'
          env:
            - name: ORIGIN
              value: 'cdssnc/github-issues-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'This application uses GitHub issues for flaw remediation.'
            - name: SATISFIES
              value: 'SA-11,SA-22,SI-2'
            - name: REPO_URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/github-snyk-check-compliance:latest'
          imagePullPolicy: Always
          name: 'github-snyk-check-compliance-si-5'
          env:
            - name: ORIGIN
              value: 'cdssnc/github-snyk-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The application uses snyk to detect package vulnerabilities.'
            - name: SATISFIES
              value: 'SA-11,SI-5'
            - name: REPO_URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-si-10'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application contains tests to validate inputs and error logging.'
            - name: SATISFIES
              value: 'SA-11,SI-10,SI-11'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/__tests__/form.test.js'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-si-17'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application implements the fail-safe policy.'
            - name: SATISFIES
              value: 'SI-17'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/fail-safe.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
      - name: compliance-checks
        persistentVolumeClaim:
          claimName: checks-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
