apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: compliance-api
  name: compliance-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: compliance-api
  template:
    metadata:
      labels:
        app: compliance-api
    spec:
      containers:
      - image: cdssnc/compliance-api
        imagePullPolicy: Always
        name: compliance-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: compliance-checks
            mountPath: /checks
        env:
          - name: CHECKS_PATH
            value: /checks
          - name: DEFINITIONS_URL
            value: https://raw.githubusercontent.com/cds-snc/ITSG-33-definitions/master/ITSG-33a.yaml
          - name: CERTIFICATION_URL
            value: https://raw.githubusercontent.com/cds-snc/ITSG-33-baselines/master/light.yaml
      initContainers:
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-au-2-apiserver'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The Kubernetes API Server Pod logs all API requests that make infrastructure changes.'
            - name: SATISFIES
              value: 'AU-2'
            - name: NEEDLE
              value: 'kube-apiserver'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sa-11-1'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses an ESLint file to do so static code analysis.'
            - name: SATISFIES
              value: 'SA-11 (1)'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/.eslintrc.json'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-si-10'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application contains tests to validate inputs.'
            - name: SATISFIES
              value: 'SI-10'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/__tests__/form.test.js'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
      - name: compliance-checks
        hostPath:
          path: /checks
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
