apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: compliance-ui
  name: compliance-ui
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: compliance-ui
  type: ClusterIP
status:
  loadBalancer: {}
