apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: compliance-ui
  name: compliance-ui
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: compliance-ui
  type: ClusterIP
status:
  loadBalancer: {}
