steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    entrypoint: "bash"
    args:
      [
        "-c",
        "cd /workspace && docker build -t gcr.io/cds-snc/compliance-api-demo:$REVISION_ID .",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args: ["push", "gcr.io/cds-snc/compliance-api-demo:$REVISION_ID"]
  - name: "gcr.io/cds-snc/compliance-api-demo:$REVISION_ID"
    id: test
    entrypoint: /bin/sh
    args: ["-c", "yarn test"]
    waitFor:
      - push
  - name: "gcr.io/cloud-builders/docker"
    id: push_docker_hub
    entrypoint: "bash"
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then docker tag gcr.io/cds-snc/compliance-api-demo:$REVISION_ID cdssnc/compliance-api-demo:$REVISION_ID && docker login docker.io -u $$DOCKER_USERNAME -p $$DOCKER_PASSWORD && docker push cdssnc/compliance-api-demo:$REVISION_ID; else exit 0; fi
    waitFor:
      - test
    secretEnv:
      ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
secrets:
  - kmsKeyName: projects/cds-snc/locations/global/keyRings/cds-keys/cryptoKeys/platform
    secretEnv:
      DOCKER_USERNAME: CiQADcHLVsVgh3MLCKbzApGWlwEexSI2QeRfk2sLd4dWiaIO0FgSNACMLY+dy5FsylxVpjGphcUlzx6dSsh65liJemmJAul1vNkeYO8IjO8BHl7/duQNoMJhJto=
      DOCKER_PASSWORD: CiQADcHLVv9z9TTyW3ZdNzmp/RSfOOx/IVtQJkdiGW9OEjCRdnwSLwCMLY+dMLdOQ+L5yJwXYRexz0BITYX/BrapjC1iyksLXZtZEdM6KcI+pPJi5r7j
