# kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user max@neuvians.net
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: max@neuvians.net
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
