apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: checks
  name: checks
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
      